// apps/quickstart-react/src/routes/DashboardView.tsx
import { Button, showToast, useSession, VerdocsTemplatesList } from '@verdocs/react-sdk';

export const DashboardView = () => {
  const { profile, endpoint } = useSession();

  // Clearing the session re-renders the route guard, which redirects to /login.
  const handleSignOut = () => {
    endpoint.clearSession();
  };

  return (
    <div>
      <header className="app-header">
        <h1>
          Verdocs React Quickstart
        </h1>
        <div className="user">
          {profile ? `${profile.first_name} ${profile.last_name} (${profile.email})` : ''}
        </div>
        <Button label="Sign Out" size="small" variant="outline" onClick={handleSignOut} />
      </header>

      <main className="app-main">
        <VerdocsTemplatesList
          onViewTemplate={({ template }) => showToast(`View template: ${template.name}`, { style: 'info' })}
          onSubmittedData={({ template }) => showToast(`Submissions for: ${template.name}`, { style: 'info' })}
          onEditTemplate={({ template }) => showToast(`Edit template: ${template.name}`, { style: 'info' })}
          onSdkError={error => showToast(error.message, { style: 'error' })}
        />
      </main>
    </div>
  );
};

// apps/quickstart-vue/src/routes/DashboardView.vue
<script setup lang="ts">
import { showToast, useSession, VerdocsButton, VerdocsTemplatesList, type ITemplateEvent, type SDKError } from '@verdocs/vue-sdk';
import { computed } from 'vue';

const { profile, endpoint } = useSession();

const userLabel = computed(() => (profile.value ? `${profile.value.first_name} ${profile.value.last_name} (${profile.value.email})` : ''));

// Clearing the session flips the route guard, which redirects to /login.
const handleSignOut = () => {
  endpoint.clearSession();
};

const onViewTemplate = ({ template }: ITemplateEvent) => showToast(`View template: ${template.name}`, { style: 'info' });
const onSubmittedData = ({ template }: ITemplateEvent) => showToast(`Submissions for: ${template.name}`, { style: 'info' });
const onEditTemplate = ({ template }: ITemplateEvent) => showToast(`Edit template: ${template.name}`, { style: 'info' });
const onSdkError = (error: SDKError) => showToast(error.message, { style: 'error' });
</script>

<template>
  <div>
    <header class="app-header">
      <h1>Verdocs Vue Quickstart</h1>
      <div class="user">
        {{ userLabel }}
      </div>
      <VerdocsButton
        label="Sign Out"
        size="small"
        variant="outline"
        @click="handleSignOut"
      />
    </header>

    <main class="app-main">
      <VerdocsTemplatesList
        @view-template="onViewTemplate"
        @submitted-data="onSubmittedData"
        @edit-template="onEditTemplate"
        @sdk-error="onSdkError"
      />
    </main>
  </div>
</template>
