// packages/react-sdk/src/controls/Pagination.tsx
import type { FC, ReactNode } from 'react';
import { integerSequence } from '@verdocs/js-sdk';
import { ChevronDoubleLeftIcon, ChevronDoubleRightIcon } from './icons';

export interface PaginationProps {
  /** The currently selected page (0-based). */
  selectedPage?: number;
  /** The total number of items. */
  itemCount?: number;
  /** The number of items displayed per page. */
  perPage?: number;
  /** Called when the user selects a page. */
  onSelectPage?: (page: number) => void;
}

const VISIBLE_PAGES = 5;

const PageButton: FC<{ selected?: boolean; onClick: () => void; children: ReactNode; label: string }> = ({ selected, onClick, children, label }) => (
  <button
    type="button"
    aria-label={label}
    aria-current={selected ? 'page' : undefined}
    onClick={onClick}
    className={`vdocs:flex vdocs:items-center vdocs:justify-center vdocs:size-8 vdocs:p-0 vdocs:text-sm vdocs:border vdocs:border-solid vdocs:rounded-ctl vdocs:cursor-pointer ${
      selected
        ? 'vdocs:bg-accent vdocs:text-white vdocs:border-accent'
        : 'vdocs:bg-surface vdocs:text-ink vdocs:border-edge-light vdocs:hover:border-accent'
    }`}>
    {children}
  </button>
);

/**
 * Display a simple pagination control with individual buttons to move through
 * the data set.
 */
export const Pagination: FC<PaginationProps> = ({ selectedPage = 0, itemCount = 0, perPage = 10, onSelectPage }) => {
  const numPages = itemCount > 0 ? Math.ceil(itemCount / perPage) : 0;
  const firstPage = Math.max(0, selectedPage - 2);
  const pagesToDisplay = integerSequence(0, numPages).slice(firstPage, firstPage + VISIBLE_PAGES);

  return (
    <nav aria-label="Pagination" className="vdocs:flex vdocs:items-center vdocs:gap-1.5 vdocs:font-sans">
      {selectedPage > 0 && (
        <PageButton label="First page" onClick={() => onSelectPage?.(0)}>
          <ChevronDoubleLeftIcon className="vdocs:size-4" />
        </PageButton>
      )}

      {firstPage > 0 && (
        <div className="vdocs:text-muted vdocs:px-1">
          ...
        </div>
      )}

      {pagesToDisplay.map(pageNumber => (
        <PageButton
          key={pageNumber}
          label={`Page ${pageNumber + 1}`}
          selected={pageNumber === selectedPage}
          onClick={() => onSelectPage?.(pageNumber)}>
          {pageNumber + 1}
        </PageButton>
      ))}

      {selectedPage < numPages - 1 && (
        <div className="vdocs:text-muted vdocs:px-1">
          ...
        </div>
      )}

      {selectedPage < numPages - 1 && (
        <PageButton label="Last page" onClick={() => onSelectPage?.(numPages - 1)}>
          <ChevronDoubleRightIcon className="vdocs:size-4" />
        </PageButton>
      )}
    </nav>
  );
};

// packages/angular-sdk/src/lib/controls/pagination.component.ts
import { integerSequence } from '@verdocs/js-sdk';
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';

const VISIBLE_PAGES = 5;

/**
 * Display a simple pagination control with individual buttons to move through
 * the data set. Pages are 0-based.
 */
@Component({
  selector: 'verdocs-pagination',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[style.display]': `'block'` },
  template: `
    <nav aria-label="Pagination" class="vdocs:flex vdocs:items-center vdocs:gap-1.5 vdocs:font-sans">
      @if (selectedPage() > 0) {
        <button type="button" aria-label="First page" [class]="buttonClasses(false)" (click)="selectPage.emit(0)">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="vdocs:size-4" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M18.75 19.5l-7.5-7.5 7.5-7.5m-6 15L5.25 12l7.5-7.5" />
          </svg>
        </button>
      }

      @if (firstPage() > 0) {
        <div class="vdocs:text-muted vdocs:px-1">...</div>
      }

      @for (pageNumber of pagesToDisplay(); track pageNumber) {
        <button
          type="button"
          [attr.aria-label]="'Page ' + (pageNumber + 1)"
          [attr.aria-current]="pageNumber === selectedPage() ? 'page' : null"
          [class]="buttonClasses(pageNumber === selectedPage())"
          (click)="selectPage.emit(pageNumber)">
          {{ pageNumber + 1 }}
        </button>
      }

      @if (selectedPage() < numPages() - 1) {
        <div class="vdocs:text-muted vdocs:px-1">...</div>
        <button type="button" aria-label="Last page" [class]="buttonClasses(false)" (click)="selectPage.emit(numPages() - 1)">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="vdocs:size-4" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11.25 4.5l7.5 7.5-7.5 7.5m-6-15l7.5 7.5-7.5 7.5" />
          </svg>
        </button>
      }
    </nav>
  `,
})
export class VerdocsPaginationComponent {
  /** The currently selected page (0-based). */
  readonly selectedPage = input(0);
  /** The total number of items. */
  readonly itemCount = input(0);
  /** The number of items displayed per page. */
  readonly perPage = input(10);

  /** Emitted when the user selects a page. */
  readonly selectPage = output<number>();

  protected readonly numPages = computed(() => (this.itemCount() > 0 ? Math.ceil(this.itemCount() / this.perPage()) : 0));
  protected readonly firstPage = computed(() => Math.max(0, this.selectedPage() - 2));
  protected readonly pagesToDisplay = computed(() =>
    integerSequence(0, this.numPages()).slice(this.firstPage(), this.firstPage() + VISIBLE_PAGES));

  protected buttonClasses(selected: boolean) {
    const base = 'vdocs:flex vdocs:items-center vdocs:justify-center vdocs:size-8 vdocs:p-0 vdocs:text-sm vdocs:border vdocs:border-solid vdocs:rounded-ctl vdocs:cursor-pointer ';
    return base + (selected ?
      'vdocs:bg-accent vdocs:text-white vdocs:border-accent' :
      'vdocs:bg-surface vdocs:text-ink vdocs:border-edge-light vdocs:hover:border-accent');
  }
}
