// packages/react-sdk/src/controls/Table.tsx
import type { ReactNode, TableHTMLAttributes } from 'react';

export interface ITableColumn<T> {
  /** Unique id for the column. When no renderCell is given, this is also the row field to display. */
  id: string;
  /** The header label. Defaults to the id. */
  header?: string;
  /** Optional custom renderer for the header cell. */
  renderHeader?: (column: ITableColumn<T>) => ReactNode;
  /** Optional custom renderer for the data cells in this column. */
  renderCell?: (column: ITableColumn<T>, row: T) => ReactNode;
}

export interface TableProps<T> extends Omit<TableHTMLAttributes<HTMLTableElement>, 'children'> {
  /** The columns to display. */
  columns: ITableColumn<T>[];
  /** The rows to display. */
  rows: T[];
  /** Called when the user clicks a column header. Useful for managing sort options. */
  onClickColumnHeader?: (column: ITableColumn<T>) => void;
  /** Called when the user clicks a row. */
  onClickRow?: (row: T) => void;
}

// The legacy table dumped raw field values into the cell, but React can only render strings
// and numbers, so anything else non-null gets String() rather than crashing the render.
// Columns needing richer output define a renderCell.
function defaultCellContent<T>(column: ITableColumn<T>, row: T): ReactNode {
  const value = (row as Record<string, unknown>)[column.id];
  if (value === null || value === undefined) {
    return null;
  }

  return typeof value === 'string' || typeof value === 'number' ? value : String(value);
}

/**
 * Display a simple table of data. Columns and data cells may have custom renderers
 * defined to support creating interactive table layouts.
 */
export default function Table<T>({ columns, rows, onClickColumnHeader, onClickRow, className = '', ...rest }: TableProps<T>) {
  return (
    <table className={`vdocs:w-full vdocs:my-2.5 vdocs:border-collapse vdocs:font-sans vdocs:text-ink ${className}`} {...rest}>
      <thead>
        <tr>
          {columns.map(column => (
            <th
              key={column.id}
              onClick={() => onClickColumnHeader?.(column)}
              className="vdocs:px-4 vdocs:py-2 vdocs:text-left vdocs:text-sm vdocs:font-semibold vdocs:text-muted">
              {column.renderHeader ? column.renderHeader(column) : column.header || column.id}
            </th>
          ))}
        </tr>
      </thead>

      <tbody>
        {/* Rows are arbitrary records with no guaranteed identity, so we key by index. The
            table keeps no per-row state, so reordered data still renders correctly. */}
        {rows.map((row, index) => (
          <tr
            key={index}
            onClick={() => onClickRow?.(row)}
            className={`vdocs:bg-surface vdocs:border vdocs:border-solid vdocs:border-edge-light ${
              onClickRow ? 'vdocs:cursor-pointer vdocs:hover:bg-accent-light/10' : ''
            }`}>
            {columns.map(column => (
              <td key={column.id} className="vdocs:px-4 vdocs:py-2 vdocs:text-sm vdocs:font-normal">
                {column.renderCell ? column.renderCell(column, row) : defaultCellContent(column, row)}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

// packages/angular-sdk/src/lib/controls/table.component.ts
import { NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input, output, TemplateRef } from '@angular/core';

export interface ITableHeaderContext<T> {
  /** The column being rendered. */
  $implicit: ITableColumn<T>;
}

export interface ITableCellContext<T> {
  /** The row being rendered. */
  $implicit: T;
  /** The column being rendered. */
  column: ITableColumn<T>;
}

export interface ITableColumn<T> {
  /** Unique id for the column. When no cellTemplate is given, this is also the row field to display. */
  id: string;
  /** The header label. Defaults to the id. */
  header?: string;
  /** Optional template for the header cell, the Angular take on React's renderHeader. The column is the implicit context. */
  headerTemplate?: TemplateRef<ITableHeaderContext<T>>;
  /** Optional template for the data cells in this column, the Angular take on React's renderCell. The row is the implicit context. */
  cellTemplate?: TemplateRef<ITableCellContext<T>>;
}

/**
 * Display a simple table of data. Columns may define header and cell templates
 * to support creating interactive table layouts. React's onClickColumnHeader and
 * onClickRow callbacks are the clickColumnHeader and clickRow outputs.
 *
 * ```html
 * <ng-template #nameCell let-row><strong>{{ row.name }}</strong></ng-template>
 * <verdocs-table [columns]="[{ id: 'name', cellTemplate: nameCell }]" [rows]="rows" />
 * ```
 */
@Component({
  selector: 'verdocs-table',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ NgTemplateOutlet ],
  host: { '[style.display]': `'block'` },
  template: `
    <table class="vdocs:w-full vdocs:my-2.5 vdocs:border-collapse vdocs:font-sans vdocs:text-ink">
      <thead>
        <tr>
          @for (column of columns(); track column.id) {
            <th
              class="vdocs:px-4 vdocs:py-2 vdocs:text-left vdocs:text-sm vdocs:font-semibold vdocs:text-muted"
              (click)="clickColumnHeader.emit(column)">
              @if (column.headerTemplate) {
                <ng-container [ngTemplateOutlet]="column.headerTemplate" [ngTemplateOutletContext]="{ $implicit: column }" />
              } @else {
                {{ column.header || column.id }}
              }
            </th>
          }
        </tr>
      </thead>

      <tbody>
        <!-- Rows are arbitrary records with no guaranteed identity, so we track by index. The
             table keeps no per-row state, so reordered data still renders correctly. -->
        @for (row of rows(); track $index) {
          <tr [class]="rowClasses()" (click)="clickRow.emit(row)">
            @for (column of columns(); track column.id) {
              <td class="vdocs:px-4 vdocs:py-2 vdocs:text-sm vdocs:font-normal">
                @if (column.cellTemplate) {
                  <ng-container [ngTemplateOutlet]="column.cellTemplate" [ngTemplateOutletContext]="{ $implicit: row, column: column }" />
                } @else {
                  {{ defaultCellContent(column, row) }}
                }
              </td>
            }
          </tr>
        }
      </tbody>
    </table>
  `,
})
export class VerdocsTableComponent<T> {
  /** The columns to display. */
  readonly columns = input.required<ITableColumn<T>[]>();
  /** The rows to display. */
  readonly rows = input.required<T[]>();
  /**
   * Adds the pointer cursor and row hover treatment. React infers this from the
   * presence of onClickRow; Angular cannot see output subscribers, so it is an
   * explicit input.
   */
  readonly clickableRows = input(false);

  /** Emitted when the user clicks a column header. Useful for managing sort options. */
  readonly clickColumnHeader = output<ITableColumn<T>>();
  /** Emitted when the user clicks a row. */
  readonly clickRow = output<T>();

  protected readonly rowClasses = computed(
    () =>
      'vdocs:bg-surface vdocs:border vdocs:border-solid vdocs:border-edge-light' +
      (this.clickableRows() ? ' vdocs:cursor-pointer vdocs:hover:bg-accent-light/10' : ''),
  );

  // The legacy table dumped raw field values into the cell; anything that isn't
  // already text gets String() rather than rendering "[object Object]" surprises
  // ad hoc. Columns needing richer output define a cellTemplate.
  protected defaultCellContent(column: ITableColumn<T>, row: T): string | number | null {
    const value = (row as Record<string, unknown>)[column.id];
    if (value === null || value === undefined) {
      return null;
    }

    return typeof value === 'string' || typeof value === 'number' ? value : String(value);
  }
}
