// packages/react-sdk/src/dialogs/PasscodeDialog.tsx
import { useState } from 'react';
import TextInput from '../controls/TextInput';
import Button from '../controls/Button';
import Dialog from './Dialog';

export interface PasscodeDialogProps {
  /** Displayed below the input in the danger color, typically after the verification endpoint rejects the passcode. */
  error?: string;
  /** Fired when the user submits the passcode they entered. The input clears for the next attempt. */
  onSubmit?: (code: string) => void;
  /** Fired when the user cancels via the Cancel button or the close control. */
  onCancel?: () => void;
}

/**
 * Prompt the signer for the passcode protecting an envelope. Purely presentational: the
 * sign embed wires onSubmit to the signer verification endpoint and reports a rejected
 * passcode back through the error prop.
 */
export default function PasscodeDialog({ error, onSubmit, onCancel }: PasscodeDialogProps) {
  const [code, setCode] = useState('');

  const handleSubmit = () => {
    onSubmit?.(code);
    setCode('');
  };

  return (
    <Dialog
      heading="Passcode Required"
      persistent
      onClose={onCancel}
      footer={(
        <div className="vdocs:flex vdocs:justify-end vdocs:gap-4">
          <Button label="Cancel" variant="outline" onClick={() => onCancel?.()} />
          <Button label="Submit" disabled={!code} onClick={handleSubmit} />
        </div>
      )}>
      <p className="vdocs:mt-0 vdocs:mb-5">
        This document is protected by a passcode. Please enter it below to proceed. If you do not have one, please contact the sender.
      </p>

      <TextInput placeholder="Enter passcode..." value={code} onChange={e => setCode(e.target.value)} />

      {error && (
        <div role="alert" className="vdocs:mt-2 vdocs:text-sm vdocs:text-danger">
          {error}
        </div>
      )}
    </Dialog>
  );
}

// packages/angular-sdk/src/lib/dialogs/passcode-dialog.component.ts
import { ChangeDetectionStrategy, Component, input, output, signal } from '@angular/core';
import { VerdocsTextInputComponent } from '../controls/text-input.component';
import { VerdocsButtonComponent } from '../controls/button.component';
import { VerdocsDialogComponent } from './dialog.component';

/**
 * Prompt the signer for the passcode protecting an envelope. Purely presentational:
 * the sign embed wires submit to the signer verification endpoint and reports a
 * rejected passcode back through the error input. React's onSubmit/onCancel
 * callbacks are this component's submit and cancel outputs.
 */
@Component({
  selector: 'verdocs-passcode-dialog',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ VerdocsDialogComponent, VerdocsButtonComponent, VerdocsTextInputComponent ],
  template: `
    <verdocs-dialog heading="Passcode Required" [persistent]="true" [footer]="footerTpl" (closed)="cancel.emit()">
      <p class="vdocs:mt-0 vdocs:mb-5">
        This document is protected by a passcode. Please enter it below to proceed. If you do not have one, please contact the sender.
      </p>

      <verdocs-text-input placeholder="Enter passcode..." [(value)]="code" />

      @if (error()) {
        <div role="alert" class="vdocs:mt-2 vdocs:text-sm vdocs:text-danger">{{ error() }}</div>
      }
    </verdocs-dialog>

    <ng-template #footerTpl>
      <div class="vdocs:flex vdocs:justify-end vdocs:gap-4">
        <verdocs-button label="Cancel" variant="outline" (click)="cancel.emit()" />
        <verdocs-button label="Submit" [disabled]="!code()" (click)="onSubmit()" />
      </div>
    </ng-template>
  `,
})
export class VerdocsPasscodeDialogComponent {
  /** Displayed below the input in the danger color, typically after the verification endpoint rejects the passcode. */
  readonly error = input('');

  /** Emitted when the user submits the passcode they entered. The input clears for the next attempt. */
  readonly submit = output<string>();
  /** Emitted when the user cancels via the Cancel button or the close control. */
  readonly cancel = output<void>();

  protected readonly code = signal('');

  protected onSubmit() {
    this.submit.emit(this.code());
    this.code.set('');
  }
}
